/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte_grafica;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frm_login extends javax.swing.JFrame {

    /**
     * Creates new form frm_login
     */
    public frm_login() {
        initComponents();
    }
    
    public boolean RevisarUsuario(String usuario){
        //Función para revisar si el usuario existe dentro de la base de datos
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `usuarios` WHERE `usuario` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, usuario);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        }   
        
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        
        return checkUser;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        lb_iniciar_sesion = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        line1 = new javax.swing.JSeparator();
        lb_contrasena = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JPasswordField();
        line2 = new javax.swing.JSeparator();
        pnl_button = new javax.swing.JPanel();
        lb_acceder = new javax.swing.JLabel();
        img_bg = new javax.swing.JLabel();
        img_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));

        lb_logo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_logo.setText("AGROQAMPO");

        lb_iniciar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_iniciar_sesion.setText("INICIAR SESIÓN");

        lb_usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_usuario.setText("USUARIO");

        txt_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_usuario.setToolTipText("");
        txt_usuario.setBorder(null);

        line1.setForeground(new java.awt.Color(0, 0, 0));

        lb_contrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_contrasena.setText("CONTRASEÑA");

        txt_contrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_contrasena.setBorder(null);

        line2.setForeground(new java.awt.Color(0, 0, 0));

        pnl_button.setBackground(new java.awt.Color(1, 166, 190));
        pnl_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_buttonMousePressed(evt);
            }
        });

        lb_acceder.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lb_acceder.setForeground(new java.awt.Color(255, 255, 255));
        lb_acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_acceder.setText("ACCEDER");
        lb_acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_accederMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_buttonLayout = new javax.swing.GroupLayout(pnl_button);
        pnl_button.setLayout(pnl_buttonLayout);
        pnl_buttonLayout.setHorizontalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_acceder, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnl_buttonLayout.setVerticalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_acceder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        img_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pexels-deneen-lt-1058401.jpg"))); // NOI18N

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_1.png"))); // NOI18N

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_usuario)
                            .addComponent(txt_usuario)
                            .addComponent(line1)
                            .addComponent(lb_contrasena)
                            .addComponent(line2)
                            .addComponent(lb_iniciar_sesion)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(img_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_logo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(img_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(img_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bgLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_logo)
                        .addGap(43, 43, 43)))
                .addComponent(lb_iniciar_sesion)
                .addGap(27, 27, 27)
                .addComponent(lb_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lb_contrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(pnl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_buttonMousePressed
        //Acceso y verificación de usuario
        
        PreparedStatement ps;
        ResultSet rs;
        
        String Usuario, Contrasena;
        Usuario = txt_usuario.getText();
        Contrasena = String.valueOf(txt_contrasena.getPassword());
        
        String query = "SELECT * FROM `usuarios` WHERE `usuario` =? AND `contrasena` =?";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, Usuario);
            ps.setString(2, Contrasena);
            
            rs = ps.executeQuery();
            
            if(rs.next()){     
                frm_main mf = new frm_main();
                mf.setVisible(true);
                mf.pack();
                this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Fallo en acceso", 2);
            }
                
            }   
            
            catch (SQLException ex){
            Logger.getLogger(frm_login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error" + ex);
            
            }       
    }//GEN-LAST:event_pnl_buttonMousePressed

    private void lb_accederMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_accederMousePressed
        //Acceso y verificación de usuario
        
        PreparedStatement ps;
        ResultSet rs;
        
        String Usuario, Contrasena;
        Usuario = txt_usuario.getText();
        Contrasena = String.valueOf(txt_contrasena.getPassword());
        
        String query = "SELECT * FROM `usuarios` WHERE `usuario` =? AND `contrasena` =?";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, Usuario);
            ps.setString(2, Contrasena);
            
            rs = ps.executeQuery();
            
            if(rs.next()){     
                frm_main mf = new frm_main();
                mf.setVisible(true);
                mf.pack();
                this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Fallo en acceso", 2);
            }
                
            }   
            
            catch (SQLException ex){
            Logger.getLogger(frm_login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error" + ex);
            
            }       
    }//GEN-LAST:event_lb_accederMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_bg;
    private javax.swing.JLabel img_logo;
    private javax.swing.JLabel lb_acceder;
    private javax.swing.JLabel lb_contrasena;
    private javax.swing.JLabel lb_iniciar_sesion;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JSeparator line1;
    private javax.swing.JSeparator line2;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPanel pnl_button;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
