/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte_grafica;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class frm_empleado extends javax.swing.JFrame {

    /**
     * Creates new form frm_empleado
     */
    public frm_empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cant1 = new javax.swing.JLabel();
        txt_cant1 = new javax.swing.JTextField();
        line8 = new javax.swing.JSeparator();
        lb_cant2 = new javax.swing.JLabel();
        txt_cant2 = new javax.swing.JTextField();
        line9 = new javax.swing.JSeparator();
        pnl_bg1 = new javax.swing.JPanel();
        pnl_bg2 = new javax.swing.JPanel();
        lb_empleado = new javax.swing.JLabel();
        line4 = new javax.swing.JSeparator();
        lb_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        line12 = new javax.swing.JSeparator();
        lb_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        line14 = new javax.swing.JSeparator();
        lb_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        line10 = new javax.swing.JSeparator();
        lb_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        line13 = new javax.swing.JSeparator();
        lb_cedula = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        line11 = new javax.swing.JSeparator();
        lb_puesto = new javax.swing.JLabel();
        txt_puesto = new javax.swing.JTextField();
        line15 = new javax.swing.JSeparator();
        img_logo1 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();

        lb_cant1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cant1.setText("Cédula:");

        txt_cant1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_cant1.setBorder(null);

        line8.setForeground(new java.awt.Color(0, 0, 0));

        lb_cant2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cant2.setText("Cédula:");

        txt_cant2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_cant2.setBorder(null);

        line9.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bg1.setBackground(new java.awt.Color(255, 255, 255));

        pnl_bg2.setBackground(new java.awt.Color(0, 102, 153));

        lb_empleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_empleado.setForeground(new java.awt.Color(255, 255, 255));
        lb_empleado.setText("Empleado");

        javax.swing.GroupLayout pnl_bg2Layout = new javax.swing.GroupLayout(pnl_bg2);
        pnl_bg2.setLayout(pnl_bg2Layout);
        pnl_bg2Layout.setHorizontalGroup(
            pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_empleado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_bg2Layout.setVerticalGroup(
            pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_empleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_id.setText("ID:");

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_id.setBorder(null);

        line12.setForeground(new java.awt.Color(0, 0, 0));

        lb_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_nombre.setBorder(null);

        line14.setForeground(new java.awt.Color(0, 0, 0));

        lb_apellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_apellido.setText("Apellido:");

        txt_apellido.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_apellido.setBorder(null);

        line10.setForeground(new java.awt.Color(0, 0, 0));

        lb_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_telefono.setText("Teléfono:");

        txt_telefono.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_telefono.setBorder(null);

        line13.setForeground(new java.awt.Color(0, 0, 0));

        lb_cedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cedula.setText("Cédula:");

        txt_cedula.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_cedula.setBorder(null);

        line11.setForeground(new java.awt.Color(0, 0, 0));

        lb_puesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_puesto.setText("Puesto:");

        txt_puesto.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_puesto.setBorder(null);

        line15.setForeground(new java.awt.Color(0, 0, 0));

        img_logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Mi_proyecto__1_-removebg-preview.png")); // NOI18N

        btn_borrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-borrar-para-siempre-48.png")); // NOI18N
        btn_borrar.setBorder(null);
        btn_borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-guardar-48.png")); // NOI18N
        btn_guardar.setBorder(null);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_imprimir.setBackground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-imprimir-48 (1).png")); // NOI18N
        btn_imprimir.setBorder(null);
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_bg1Layout = new javax.swing.GroupLayout(pnl_bg1);
        pnl_bg1.setLayout(pnl_bg1Layout);
        pnl_bg1Layout.setHorizontalGroup(
            pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                .addComponent(pnl_bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_bg1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(line12)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addComponent(lb_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(line14)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addComponent(lb_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addComponent(lb_apellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(line10)
                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line13)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guardar))
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addComponent(lb_cedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cedula))
                            .addComponent(line11)
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addComponent(lb_telefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addComponent(lb_puesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
        );
        pnl_bg1Layout.setVerticalGroup(
            pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg1Layout.createSequentialGroup()
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(img_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_bg1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(pnl_bg2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_telefono)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_cedula)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_apellido)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_puesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_borrar)
                    .addComponent(btn_guardar)
                    .addComponent(btn_imprimir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:

        txt_id.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_telefono.setText("");
        txt_cedula.setText("");
        txt_puesto.setText("");
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:

        Connection con = MyConnection.getConnection();
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(frm_producto.class.getResource("/Reportes/Reporte_empleado.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte de empleado");

            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_btn_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JLabel img_logo1;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_cant1;
    private javax.swing.JLabel lb_cant2;
    private javax.swing.JLabel lb_cedula;
    private javax.swing.JLabel lb_empleado;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_puesto;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JSeparator line10;
    private javax.swing.JSeparator line11;
    private javax.swing.JSeparator line12;
    private javax.swing.JSeparator line13;
    private javax.swing.JSeparator line14;
    private javax.swing.JSeparator line15;
    private javax.swing.JSeparator line4;
    private javax.swing.JSeparator line8;
    private javax.swing.JSeparator line9;
    private javax.swing.JPanel pnl_bg1;
    private javax.swing.JPanel pnl_bg2;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cant1;
    private javax.swing.JTextField txt_cant2;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_puesto;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
