/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte_grafica;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class frm_factura extends javax.swing.JFrame {

    /**
     * Creates new form frm_factura
     */
    public frm_factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg1 = new javax.swing.JPanel();
        pnl_bg2 = new javax.swing.JPanel();
        lb_factura = new javax.swing.JLabel();
        line1 = new javax.swing.JSeparator();
        lb_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        line3 = new javax.swing.JSeparator();
        lb_cliente = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        line7 = new javax.swing.JSeparator();
        lb_vendedor = new javax.swing.JLabel();
        txt_vendedor = new javax.swing.JTextField();
        line4 = new javax.swing.JSeparator();
        lb_pago = new javax.swing.JLabel();
        txt_pago = new javax.swing.JTextField();
        line11 = new javax.swing.JSeparator();
        lb_fecha = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        line6 = new javax.swing.JSeparator();
        lb_fechavencimiento = new javax.swing.JLabel();
        txt_fechavencimiento = new javax.swing.JTextField();
        line5 = new javax.swing.JSeparator();
        lb_monto = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        line10 = new javax.swing.JSeparator();
        lb_Itbis = new javax.swing.JLabel();
        txt_Itbis = new javax.swing.JTextField();
        line12 = new javax.swing.JSeparator();
        img_logo1 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bg1.setBackground(new java.awt.Color(255, 255, 255));

        pnl_bg2.setBackground(new java.awt.Color(0, 102, 153));

        lb_factura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_factura.setForeground(new java.awt.Color(255, 255, 255));
        lb_factura.setText("Factura");

        javax.swing.GroupLayout pnl_bg2Layout = new javax.swing.GroupLayout(pnl_bg2);
        pnl_bg2.setLayout(pnl_bg2Layout);
        pnl_bg2Layout.setHorizontalGroup(
            pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_factura))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        pnl_bg2Layout.setVerticalGroup(
            pnl_bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_factura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_id.setText("ID:");

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_id.setBorder(null);

        line3.setForeground(new java.awt.Color(0, 0, 0));

        lb_cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cliente.setText("Cliente:");

        txt_cliente.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_cliente.setBorder(null);

        line7.setForeground(new java.awt.Color(0, 0, 0));

        lb_vendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_vendedor.setText("Vendedor:");

        txt_vendedor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_vendedor.setBorder(null);

        line4.setForeground(new java.awt.Color(0, 0, 0));

        lb_pago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_pago.setText("Forma de pago:");

        txt_pago.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_pago.setBorder(null);

        line11.setForeground(new java.awt.Color(0, 0, 0));

        lb_fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_fecha.setText("Fecha:");

        txt_fecha.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_fecha.setBorder(null);
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });

        line6.setForeground(new java.awt.Color(0, 0, 0));

        lb_fechavencimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_fechavencimiento.setText("Fecha vencimieto:");

        txt_fechavencimiento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_fechavencimiento.setBorder(null);

        line5.setForeground(new java.awt.Color(0, 0, 0));

        lb_monto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_monto.setText("Monto:");

        txt_monto.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_monto.setBorder(null);

        line10.setForeground(new java.awt.Color(0, 0, 0));

        lb_Itbis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Itbis.setText("Itbis:");

        txt_Itbis.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txt_Itbis.setBorder(null);

        line12.setForeground(new java.awt.Color(0, 0, 0));

        img_logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Mi_proyecto__1_-removebg-preview.png")); // NOI18N

        btn_borrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-borrar-para-siempre-48.png")); // NOI18N
        btn_borrar.setBorder(null);
        btn_borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-guardar-48.png")); // NOI18N
        btn_guardar.setBorder(null);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_imprimir.setBackground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-imprimir-48 (1).png")); // NOI18N
        btn_imprimir.setBorder(null);
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_bg1Layout = new javax.swing.GroupLayout(pnl_bg1);
        pnl_bg1.setLayout(pnl_bg1Layout);
        pnl_bg1Layout.setHorizontalGroup(
            pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                .addComponent(pnl_bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_bg1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardar))
                            .addGroup(pnl_bg1Layout.createSequentialGroup()
                                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                                        .addComponent(lb_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(line3)
                                    .addComponent(line7)
                                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                                        .addComponent(lb_cliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_cliente))
                                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                                        .addComponent(lb_vendedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_vendedor))
                                    .addComponent(line4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(line11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                                        .addComponent(lb_id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(line10)
                                        .addComponent(line6)
                                        .addComponent(lb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(line5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bg1Layout.createSequentialGroup()
                                            .addComponent(lb_fechavencimiento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_fechavencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnl_bg1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnl_bg1Layout.createSequentialGroup()
                                                    .addComponent(lb_Itbis)
                                                    .addGap(14, 14, 14)
                                                    .addComponent(txt_Itbis))
                                                .addGroup(pnl_bg1Layout.createSequentialGroup()
                                                    .addComponent(lb_monto)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addComponent(line12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(53, 53, 53))
        );
        pnl_bg1Layout.setVerticalGroup(
            pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bg1Layout.createSequentialGroup()
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pnl_bg2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(img_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_fecha)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_cliente)
                            .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_fechavencimiento)
                            .addComponent(txt_fechavencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_vendedor)
                            .addComponent(txt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(line11, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_bg1Layout.createSequentialGroup()
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_monto)
                            .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Itbis)
                            .addComponent(txt_Itbis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(pnl_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar)
                    .addComponent(btn_borrar)
                    .addComponent(btn_imprimir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:

        txt_id.setText("");
        txt_cliente.setText("");
        txt_vendedor.setText("");
        txt_fecha.setText("");
        txt_fechavencimiento.setText("");
        txt_monto.setText("");
        txt_Itbis.setText("");
        
        
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:

        Connection con = MyConnection.getConnection();
        try{
            JasperReport jr = (JasperReport) JRLoader.loadObject(frm_factura.class.getResource("/Reportes/Reporte_factura.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("Titulo", "Reporte factura");

            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JLabel img_logo1;
    private javax.swing.JLabel lb_Itbis;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_factura;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_fechavencimiento;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_monto;
    private javax.swing.JLabel lb_pago;
    private javax.swing.JLabel lb_vendedor;
    private javax.swing.JSeparator line1;
    private javax.swing.JSeparator line10;
    private javax.swing.JSeparator line11;
    private javax.swing.JSeparator line12;
    private javax.swing.JSeparator line3;
    private javax.swing.JSeparator line4;
    private javax.swing.JSeparator line5;
    private javax.swing.JSeparator line6;
    private javax.swing.JSeparator line7;
    private javax.swing.JPanel pnl_bg1;
    private javax.swing.JPanel pnl_bg2;
    private javax.swing.JTextField txt_Itbis;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_fechavencimiento;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_pago;
    private javax.swing.JTextField txt_vendedor;
    // End of variables declaration//GEN-END:variables
}
