/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroqampo_proy;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class frm_jOption extends javax.swing.JFrame {

    /**
     * Creates new form frm_jOption
     */
    public frm_jOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnenviar = new javax.swing.JButton();
        nomlabel = new javax.swing.JLabel();
        nombrefields = new javax.swing.JTextField();
        apellidolabel = new javax.swing.JLabel();
        apellidofield = new javax.swing.JTextField();
        razalabel = new javax.swing.JLabel();
        edadlabel = new javax.swing.JLabel();
        razafield = new javax.swing.JTextField();
        edade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(179, 220, 216));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titulo.setText("Probanding");

        btnenviar.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Downloads\\icons8-guardar-48.png")); // NOI18N
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        nomlabel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        nomlabel.setText(" Nombre");
        nomlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nomlabelMousePressed(evt);
            }
        });

        nombrefields.setForeground(new java.awt.Color(204, 204, 204));
        nombrefields.setText("Ingrese Nombre");
        nombrefields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombrefieldsMousePressed(evt);
            }
        });

        apellidolabel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        apellidolabel.setText("Apellido");
        apellidolabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidolabelMousePressed(evt);
            }
        });

        apellidofield.setForeground(new java.awt.Color(204, 204, 204));
        apellidofield.setText("Ingrese apelldio");
        apellidofield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidofieldMousePressed(evt);
            }
        });

        razalabel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        razalabel.setText("Raza");
        razalabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                razalabelMousePressed(evt);
            }
        });

        edadlabel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        edadlabel.setText("Edad");
        edadlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                edadlabelMousePressed(evt);
            }
        });

        razafield.setForeground(new java.awt.Color(204, 204, 204));
        razafield.setText("Ingerse RAZA");
        razafield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                razafieldMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomlabel)
                                .addComponent(nombrefields, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addComponent(apellidolabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                    .addComponent(apellidofield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(razalabel))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(razafield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(149, 149, 149)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edadlabel)
                                .addComponent(edade)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(titulo)
                            .addGap(40, 40, 40)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnenviar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(titulo)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomlabel)
                    .addComponent(apellidolabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrefields, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidofield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razalabel)
                    .addComponent(edadlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razafield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
        
         JOptionPane.showMessageDialog(null, "Haz enviado el formulario ");

    }//GEN-LAST:event_btnenviarActionPerformed

    private void nombrefieldsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrefieldsMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Llene el campo!");
    }//GEN-LAST:event_nombrefieldsMousePressed

    private void nomlabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomlabelMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aqui escriba su nombre");
    }//GEN-LAST:event_nomlabelMousePressed

    private void razafieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razafieldMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Llene el campo!");
        
    }//GEN-LAST:event_razafieldMousePressed

    private void apellidofieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidofieldMousePressed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(null, "Llene el campo!");
    }//GEN-LAST:event_apellidofieldMousePressed

    private void apellidolabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidolabelMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Aqui escriba su apellido");
    }//GEN-LAST:event_apellidolabelMousePressed

    private void razalabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razalabelMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Aqui escriba su raza");
    }//GEN-LAST:event_razalabelMousePressed

    private void edadlabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadlabelMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Aqui escriba su edad");
    }//GEN-LAST:event_edadlabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_jOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_jOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidofield;
    private javax.swing.JLabel apellidolabel;
    private javax.swing.JButton btnenviar;
    private javax.swing.JSpinner edade;
    private javax.swing.JLabel edadlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrefields;
    private javax.swing.JLabel nomlabel;
    private javax.swing.JTextField razafield;
    private javax.swing.JLabel razalabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
